config/routes.rb
Rails.application.routes.draw do
  resources :episodes, only: [:index, :show, :update, :saw, :create, :new, :destroy, :edit]  do
    resources :comments
  end
  resources :seasons
  resources :companies
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
  resources :shows
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :episode
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :show_companies
  has_many :shows, through: :show_companies
end

app/models/episode.rb
class Episode < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :season, optional:true
  has_many :comments
  has_and_belongs_to_many :users
end

app/models/season.rb
class Season < ApplicationRecord
  belongs_to :show, optional:true
  has_many :episodes
end

app/models/show.rb
class Show < ApplicationRecord
  mount_uploader :image, ImageUploader
  has_many :seasons
  has_many :show_companies
  has_many :companies, through: :show_companies
end

app/models/show_company.rb
class ShowCompany < ApplicationRecord
  belongs_to :show
  belongs_to :company
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :username, presence: true, uniqueness: true

  has_and_belongs_to_many :episodes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = %i(username)
    devise_parameter_sanitizer.permit(:sign_up, keys: added_attrs)
    devise_parameter_sanitizer.permit(:account_update, keys: added_attrs)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @episode = Episode.find(params[:episode_id])
    @comment = @episode.comments.create(params[:comment].permit(:content))
    redirect_to episode_path(@episode)
  end

  def destroy
    @episode = Episode.find(params[:episode_id])
    @comment = @episode.comments.find(params[:id])
    @comment.destroy
    redirect_to episode_path(@episode)
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: %i[new create edit update destroy]

  # GET /companies
  def index
    @companies = Company.all
  end

  # GET /companies/1
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  def create
    @company = Company.new(company_params)
    if @company.save
      redirect_to @company, notice: 'Company was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /companies/1
  def update
      if @company.update(company_params)
        redirect_to @company, notice: 'Company was successfully updated.'
      else
        render :edit
      end
  end

  # DELETE /companies/1
  def destroy
    @company.destroy
      redirect_to companies_url, notice: 'Company was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :icon)
    end
end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
  before_action :set_episode, only: %i[show edit update destroy saw]
  before_action :authenticate_user!, only: %i[new create edit update destroy saw]

  def index
    @episodes = Episode.includes(:season)
  end

  def show
  end

  def new
    @episode = Episode.new
  end

  def edit
  end

  def create
    @episode = Episode.new(episode_params)
      if @episode.save
        redirect_to @episode, notice: 'Episode was successfully created.'
      else
        render :new
      end
  end

  def update
      if @episode.update(episode_params)
        redirect_to @episode, notice: 'Episode was successfully updated.'
      else
        render :edit
      end
  end

  def destroy
    @episode.destroy
    redirect_to episodes_url, notice: 'Episode was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_episode
      @episode = Episode.includes(:season).find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def episode_params
      params.require(:episode).permit(:name, :storyline, :image, :runtime, :release_at, { user_ids:[] })
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @episodes = Episode.where(created_at: Time.zone.now.beginning_of_day..Time.zone.now.end_of_day)
    @shows = Show.where(release_date: Time.zone.now.beginning_of_day..Time.zone.now.end_of_day)
  end
end

app/controllers/seasons_controller.rb
class SeasonsController < ApplicationController
  before_action :set_season, only: %i[show edit update destroy]
  before_action :authenticate_user!, only: %i[new create edit update destroy]

  def index
    @seasons = Season.includes(:show)
  end

  def show
  end

  def new
    @season = Season.new
  end

  def edit
  end

  def create
    @season = Season.new(season_params)
      if @season.save
        redirect_to @season, notice: 'Season was successfully created.'
      else
        render :new
      end
  end

  def update
      if @season.update(season_params)
        redirect_to @season, notice: 'Season was successfully updated.'
      else
        render :edit
      end
  end

  def destroy
    @season.destroy
      redirect_to seasons_url, notice: 'Season was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_season
      @season = Season.includes(:show).find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def season_params
      params.require(:season).permit(:number, :show_id)
    end
end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
  before_action :set_show, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: %i[new create edit update destroy]

  def index
    @shows = Show.includes(:companies)
  end

  def show
  end

  def new
    @show = Show.new
  end

  def edit
  end

  def create
    @show = Show.new(show_params)
    if @show.save
      redirect_to @show, notice: 'La série a bien été ajoutée.'
    else
      render :new
    end
  end

  def update
    if @show.update(show_params)
      redirect_to @show, notice: 'La série a bien été mise à jour.'
    else
      render :edit
    end
  end

  def destroy
    if @show.destroy
      redirect_to shows_url
    else
      render 'show'
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_show
    @show = Show.includes(:companies).find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def show_params
    params.require(:show).permit(:title, :storyline, :release_date, :end_date, :image, company_ids: [])
  end
end

app/controllers/users_episodes_controller.rb
class UsersEpisodesController < ApplicationController
  def edit
  end

  def create
    @episode = UsersEpisodes.new(episode_params)
    if @episode.save
      redirect_to @episode, notice: 'Episode was successfully created.'
    else
      render :new
    end
  end

  def update
    if @episode.update(episode_params)
      redirect_to @episode, notice: 'Episode was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @episode.destroy
    redirect_to episodes_url, notice: 'Episode was successfully destroyed.'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/episodes_helper.rb
module EpisodesHelper
end

app/helpers/seasons_helper.rb
module SeasonsHelper
end

app/views/comments/_comment.html.erb
<div class="box">
  <article class="media">
    <div class="media-content">
      <div class="content">
        <p>
          <%= comment.content %>
        </p>
      </div>
    </div>
    <%= link_to 'Delete', [comment.episode, comment],
                method: :delete, class: "button is-danger", data: { confirm: 'Are you sure?' } %>
  </article>

</div>

app/views/comments/_form.html.erb
<%= simple_form_for([@episode, @episode.comments.build]) do |f| %>
  <div class="field">
    <div class="control">
      <%= f.input :content, input_html: { class: 'input' }, wrapper: false, label_html: { class: 'label' } %>
    </div>
  </div>
  <%= f.button :submit, 'Leave a reply', class: "button is-primary" %>
<% end %>

app/views/companies/_companies_list.html.erb
<% if companies.any? %>
  <% companies.map do |c| %>
    <%= link_to c do %>
        <%= c.name %>
    <% end %>
  <% end %>
<%else%>
  &empty;
<%end%>

app/views/companies/_form.html.erb
<%= simple_form_for(@company) do |form| %>
  <div class="row">
    <div class="form-group col-lg-6">
      <%= form.input :name, label: 'Nom', class: 'form-control' %>
    </div>
    <div class="form-group col-lg-6">
      <%= form.input :icon, label: 'Image de couverture', class: 'form-control' %>
    </div>
  </div>

  <div class="actions">
    <%= form.submit 'Enregistrer', class: 'btn btn-primary' %>
    <%= link_to 'Retour à la liste des sociétés de production', companies_path, class: 'btn btn-default' %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Édition d'une société de production</h1>

<%= render 'form', company: @company %>

app/views/companies/index.html.erb
<h1>Liste des sociétés de production</h1>

<% if @companies.any?%>
  <table class="table">
    <thead>
    <tr>
      <th>Nom</th>
      <th>Icône</th>
    </tr>
    </thead>
    <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.name %></td>
        <td><%= company.icon %></td>
        <td>
          <%= link_to 'Afficher', company, class: 'btn btn-info' %>
          <% if user_signed_in? %>
            <%= link_to 'Modifier', edit_company_path(company), class: 'btn btn-warning' %>
            <%= link_to 'Supprimer', company,
                        method: :delete,
                        data: {
                            confirm: 'Etes-vous sûr(e) de vouloir supprimer cette société de production ?'
                        },
                        class: 'btn btn-danger' %>
          <% end %>
        </td>
      </tr>
    <%end%>
    </tbody>
  </table>
<%else%>
  <p>
    Il n'y a pas encore de société de production.
  </p>
<%end%>
<% if user_signed_in? %>
  <p>
    <%= link_to 'Ajouter une société de production', new_company_path, class: 'btn btn-success' %>
  </p>
<% end %>

app/views/companies/new.html.erb
<h1>Ajouter une société de production</h1>

<%= render 'form', company: @company %>

app/views/companies/show.html.erb
<h1>Affichage d'une société de production</h1>

<p>Name : <%= @company.name %></p>

<p>Icon : <%= @company.icon %></p>

<p>
  <% if user_signed_in? %>
    <%= link_to 'Modifier', edit_company_path(@company), class: 'btn btn-warning' %>
  <% end %>
  <%= link_to 'Retour à la liste des société de production', companies_path, class: 'btn btn-default' %>
</p>

app/views/episodes/_form.html.erb
<%= simple_form_for(@episode) do |f| %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :storyline %>
    <%= f.input :image, as: :file%>
    <%= f.input :runtime %>
    <%= f.input :release_at %>
  </div>
  <div class="row">
    <div class="form-group col-lg-6">
      <%= f.association :season, label: 'Saison', class: 'form-control' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/episodes/_saw.html.erb
<%= form_for(@episode.users.build(:user_ids[] => current_user.id)) do |f| %>
  <%= f.hidden_field :user_ids %>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>



<%= simple_form_for(@episode) do |f| %>

  <%= f.hidden_field :name %>
  <%= f.hidden_field :storyline %>
  <%= f.hidden_field :image, as: :file%>
  <%= f.hidden_field :runtime %>
  <%= f.hidden_field :release_at %>
  <%= f.hidden_field :release_at %>

  <% for user in User.all %>
    <div>
      <%= check_box_tag "user[episode_ids][]", user.id, user.episodes.include?(user) %>
      <%= user.username %>
    </div>
  <% end %>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/episodes/edit.html.erb
<h1>Editing Episode</h1>

<%= render 'form', episode: @episode %>

<%= link_to 'Show', @episode %> |
<%= link_to 'Back', episodes_path %>

app/views/episodes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Episodes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Storyline</th>
      <th>Cover</th>
      <th>Runtime</th>
      <th>Release at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @episodes.each do |episode| %>
      <tr>
        <td><%= episode.name %></td>
        <td><%= episode.storyline %></td>
        <td><%= episode.cover %></td>
        <td><%= episode.runtime %></td>
        <td><%= episode.release_at %></td>
        <td><%= link_to 'Show', episode %></td>
        <td><%= link_to 'Edit', edit_episode_path(episode) %></td>
        <td><%= link_to 'Destroy', episode, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Episode', new_episode_path %>

app/views/episodes/new.html.erb
<h1>New Episode</h1>

<%= render 'form', episode: @episode %>

<%= link_to 'Back', episodes_path %>

app/views/episodes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <%= image_tag @episode.image_url%>
</p>


<p>
  <strong>Titre :</strong>
  <%= @episode.name %>
</p>

<p>
  <strong>Storyline:</strong>
  <%= @episode.storyline %>
</p>

<p>
  <strong>Runtime:</strong>
  <%= @episode.runtime %> minutes
</p>

<p>
  <strong>Release at:</strong>
  <%= @episode.release_at %>
</p>

<section class="section comments">
  <div class="container">
    <h2 class="subtitle is-5"><strong><%= @episode.comments.count %></strong> Comments</h2>
    <%= render @episode.comments %>
    <div class="comment-form">
      <hr />
      <h3 class="subtitle is-3">Leave a reply</h3>
      <%= render 'comments/form' %>
    </div>
  </div>
</section>


<%= link_to 'Edit', edit_episode_path(@episode) %> |
<%= link_to 'Back', episodes_path %>

app/views/home/index.html.erb
<h1>
  Optimize your watch !
  <%= Rails.application.class.parent_name %> !
</h1>

<div class="section">
  <p>Épisodes ajouté aujourd'hui </p>
  <% @episodes.each do |episode| %>
    <%= link_to episode do %>
      <%= episode.name %>
    <% end %>
  <% end %>
</div>

<div class="section">
  <p>Nouvelles série qui commencent aujourd'hui </p>
  <% @shows.each do |show| %>
    <%= link_to show do %>
      <%= show.title %>
    <% end %>
  <% end %>
</div>

app/views/seasons/_episodes_list.html.erb
<% if episodes.any? %>
  <% episodes.map do |e| %>
    <%= link_to e do %>
      - <%= e.name %>
    <% end %>
  <% end %>
<%else%>
  &empty;
<% end %>

app/views/seasons/_form.html.erb
<%= simple_form_for(@season) do |form| %>

  <div class="row">
    <div class="form-group col-lg-6">
      <%= form.input :number, label: 'Numéro', class: 'form-control' %>
    </div>
  </div>

  <div class="row">
    <div class="form-group col-lg-6">
      <%= form.association :show, label: 'Série', class: 'form-control' %>
    </div>
  </div>
  <div class="actions">
    <%= form.submit 'Enregistrer', class: 'btn btn-primary' %>
    <%= link_to 'Retour à la liste des saisons', seasons_path, class: 'btn btn-default' %>
  </div>
<% end %>

app/views/seasons/edit.html.erb
<h1>Édition d'une Saison</h1>

<%= render 'form', season: @season %>

app/views/seasons/index.html.erb
<h1>Liste des saisons</h1>

<% if @seasons.any?%>
  <table class="table">
    <thead>
    <tr>
      <th>Numéro</th>
      <th>Série</th>
    </tr>
    </thead>
    <tbody>
    <% @seasons.each do |season| %>
      <tr>
        <td><%= season.number %></td>
        <td>
          <% if season.show.nil? %>
            &empty;
          <% else %>
            <%= season.show.title %>
          <% end %>
        </td>
        <td>
          <%= link_to 'Afficher', season, class: 'btn btn-info' %>
          <% if user_signed_in? %>
            <%= link_to 'Modifier', edit_season_path(season), class: 'btn btn-warning' %>
            <%= link_to 'Supprimer', season,
                        method: :delete,
                        data: {
                            confirm: 'Etes-vous sûr(e) de vouloir supprimer cette saison ?'
                        },
                        class: 'btn btn-danger' %>
          <% end %>
        </td>
      </tr>
    <%end%>
    </tbody>
  </table>
<%else%>
  <p>
    Il n'y a pas encore de saison.
  </p>
<%end%>
<% if user_signed_in? %>
  <p>
    <%= link_to 'Ajouter une saison', new_season_path, class: 'btn btn-success' %>
  </p>
<% end %>

app/views/seasons/new.html.erb
<h1>Nouvelle Saison</h1>

<%= render 'form', season: @season %>

app/views/seasons/show.html.erb
<h1>Saison <%= @season.number %> <% if !@season.show.nil? %> de <%= @season.show.title %><% end %></h1>

<p>Numéro: <%= @season.number %></p>
<p>
  Série:
  <% show = @season.show %>
  <% if show.nil? %>
    &empty;
  <% else %>
    <%= show.title %>
  <% end %>
</p>
<p>
  Liste des épisodes :
  <br>
  <%= render 'seasons/episodes_list', episodes: @season.episodes %>
</p>
<p>
  <% if user_signed_in? %>
    <%= link_to 'Modifier', edit_season_path(@season), class: 'btn btn-warning' %>
  <% end %>
  <%= link_to 'Retour à la liste des saisons', seasons_path, class: 'btn btn-default' %>
</p>

app/views/shows/_form.html.erb
<%= simple_form_for(show) do |form| %>
  <div class="row">
    <div class="form-group col-lg-6">
      <%= form.input :title, label:'Titre', class: 'form-control' %>
    </div>
    <div class="form-group col-lg-6">
      <%= form.input :storyline, label:'Synopsis',class: 'form-control' %>
    </div>
  </div>
  <div class="row">
    <div class="form-group col-lg-6">
      <%= form.input :release_date, label: 'Date de la première diffusion', class: 'form-control' %>
    </div>
    <div class="form-group col-lg-6">
      <%= form.input :end_date, label: 'Date de la dernière diffusion', class: 'form-control' %>
    </div>
  </div>
  <div class="row">
    <div class="form-group col-lg-6">
      <%= form.input :cover, label: 'Image', class: 'form-control' %>
    </div>
    <div class="form-group col-lg-6">
      <%= form.association :companies, as: :check_boxes, label: 'Maisons de production ', class: 'form-control' %>
    </div>
  </div>
  <div class="actions">
    <%= form.submit 'Enregistrer', class: 'btn btn-primary' %>
    <%= link_to 'Retour à la liste des séries', shows_path, class: 'btn btn-default' %>
  </div>
<%end%>

app/views/shows/_seasons_list.html.erb
<% if seasons.any? %>
  <% seasons.map do |s| %>
    <%= link_to s do %>
      <div class="panel panel-default">
        <div class="panel-heading">
          <h4 class="panel-title">
            <a data-toggle="collapse" data-parent="#accordion" href="#collapse<%= s.number %>">Saison <%= s.number %></a>
          </h4>
        </div>
        <div id="collapse<%= s.number %>" class="panel-collapse collapse">
          <div class="panel-body"><%= render 'seasons/episodes_list', episodes: s.episodes %></div>
        </div>
      </div>
    <% end %>
  <% end %>
<%else%>
  &empty;
<% end %>

app/views/shows/edit.html.erb
<h1>Edition d'une série</h1>

<%= render 'form', show: @show %>

app/views/shows/index.html.erb
<h1>Liste des séries</h1>

<% if @shows.any? %>
  <table class="table">
    <thead>
    <tr>
      <th>Nom</th>
      <th>Sociétés de production</th>
      <th colspan="3"></th>
    </tr>
    </thead>
    <tbody>
    <% @shows.each do |show| %>
      <tr>
        <td><%= show.title %></td>
        <td>
          <%= render 'companies/companies_list', companies: show.companies %>
        </td>
        <td>
          <%= link_to 'Afficher', show, class: 'btn btn-info' %>
          <% if user_signed_in? %>
          <%= link_to 'Modifier', edit_show_path(show), class: 'btn btn-warning' %>
          <%= link_to 'Supprimer', show,
                      method: :delete,
                      data: {
                          confirm: 'Etes-vous sûr(e) de vouloir supprimer cette série ?'
                      },
                      class: 'btn btn-danger' %>
          <% end %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% else %>
  <p>
    Il n'y a pas encore de série.
  </p>
<% end %>
<% if user_signed_in? %>
<p>
  <%= link_to 'Ajouter une série', new_show_path, class: 'btn btn-success' %>
</p>
<% end %>

app/views/shows/new.html.erb
<h1>Ajout d'une série</h1>

<%= render 'form', show: @show %>

app/views/shows/show.html.erb
<h1>Affichage d'une série</h1>

<p>Titre : <%= @show.title %></p>
<p>Image de couverture : <%= @show.cover %></p>
<p>Synopsis : <%= @show.storyline %></p>
<p>Date de la première diffusion : <%= @show.release_date %></p>
<p>Date de la dernière diffusion : <%= @show.end_date %></p>
<p>
  Sociétés de production:
  <%= render 'companies/companies_list', companies: @show.companies %>
</p>

<p>
  <%= link_to 'New Episode', new_episode_path %>
  mettre :
  - add
  - commentaires
</p>

<p>
<h3>Liste des saisons :</h3>
    <div class="panel-group" id="accordion">
      <%= render 'shows/seasons_list', seasons: @show.seasons %>
    </div>
  <br>
</p>

<p>
  <% if user_signed_in? %>
    <%= link_to 'Modifier', edit_show_path(@show), class: 'btn btn-warning' %>
  <% end %>
  <%= link_to 'Retour à la liste des séries', shows_path, class: 'btn btn-default' %>
</p>

app/views/users_episodes/_form.html.erb
<%= simple_form_for(@users_episodes) do |f| %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :storyline %>
    <%= f.input :image, as: :file%>
    <%= f.input :runtime %>
    <%= f.input :release_at %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>